insert into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) values(10001,'Mahesh','Learn Spring Boot',CURRENT_DATE(),FALSE);
insert into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) values(10002,'Mahesh','Learn Spring MVC',CURRENT_DATE(),FALSE);
insert into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) values(10003,'Mahesh','Learn Spring SECURITY',CURRENT_DATE(),FALSE);
insert into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) values(10004,'Mahesh','Learn Spring JPA',CURRENT_DATE(),FALSE);